name: Optimize images

on:
  push:
    paths: ["images/**"]

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compress images
        uses: calibreapp/image-actions@1.1.0
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
